qcar2_behavior_tree_manager:
  ros__parameters:
    tick_hz: 5.0
    require_tf: true # Set to true when SLAM/localization is running
    goal_reached_distance: 0.35
    goal_timeout_sec: 900.0
    goal_frame_id: map

    goal_output_topic: /bt/goal #cambiar al nuevo topico
    state_output_topic: /bt/state
    mode_output_topic: /bt/mode_hybrid
    mode_numeric_output_topic: /bt/mode_hybrid_numeric
    default_mode_hybrid: HYBRID

    mode_code_stop: 0.0
    mode_code_hybrid: 1.0
    mode_code_pid: 2.0

    goal_1: [-1.84, 4.99, 0.0]
    goal_2: [-0.65, 1.63, 0.0]
    goal_3: [1.155, 4.433, 0.0]
    goal_4: [0.0, 0.0, 0.0]

    additional_goals: []

    mission_loop:
      - set_mode:HYBRID
      - set_led:init
      - wait:3.0
      - set_led:to_pickup
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - wait:4.0
      - set_led:pickup_done
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - set_led:dropoff_done
      - wait:5.0
      - set_led:idle
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - set_led:idle
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - set_led:idle
      - wait:15.0
      - set_led:idle
      - set_mode:STOPPED
